language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: D7XmJq7/Vw1a7076BPDA8Ug91na/G3AFMTwKR3SECbIxtaVDJFkUupdHOQ456v8ds/43xw2BV3uUlBEOswNUqSf1JkDAkTdlutlwLMYCxkuKC2VHflLnvduCV7Lhy/rOImroW3NDfnKZFXVogwzWGF4ycNbNtx0e8HdcdIZVkpQNN0SWGu19fg7cQpRQWp9fChmj55B3Dit6hF6I4VLhxOm2pRXbZ1RYfsgGh0jagJvXRSea/oaVREOFLF+14xGxRWKuT+baIhl7MeV2ga/h9ZPuP6qLrC2zd+uxKqfelxxLTw80V5PjkYv4QGoMGwNyDGPFnKm7aInpe82AUdewnO1ivw+pn2hyKykP/6ga0s3qAaRfF/oAlBb53zqbPZIL4pfZItUTtR4F38L8gEwdsjo1Wk0NcE5eXyKuwOPKJJBV9VbQ4TbaoVi+sBjW877Q0DwXB5wXv+CLCSpDk4PzRWK81DM5PfrduTKy9KsD/VeCgNSO28H3FhXvHqsZEGewmM0lxEdTlUm7dp4dpIVbLATXY0jt3k7lBt4qgQ1gO+E7X33jPLuuAxtmt+uxo7AwzIaf2lD++jU1uZbYVcvxlqUCOpT7c6NRjKJBtXoHZIBE8oc8NKB3MHJXDVqP2wiOpfkYR5XvLUd5ELzz+b9CkjM9XZloTYIiE2qVEUtXEqs=
  on:
    tags: true
    repo: scopeta/focusedme
    python: 3.8
