language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: U3rnTQLz/fZGSpMKRDFfIdKI+8E2SKWf2l+JZ2NExaULR6EY2zvN+1HT9IRguUr8qfZ/UsKdL3lpwbftNDWmRzO8IbQcbgBUOj7qQQSIDuAuU4BeU2KH5A4YAsfFhNZiE9PgsRMZSZHvcWf492vEY5VKXnGSWC1yuEt0LkYl6qTaZoVDxudnILH9pNjuSM1Uueyyo+0Rk8lvrJ3bZC5n5IHwL8kPW/ExgRFdTXZh1N1h6yYVUMTWIe000INDRqSEJ4DzHQhrjJfSRWdqsmjBgAIzVCCYpgwdlbUXZIQD5rfocyO1lIgc0NPkiGTqUDmdwIf3HR0eUQaOqmMzw1UGnaBf3L106zXDFdt5VTppf3vvRJbMxAeGMNF8byyIVAxDAEzQcFqLKhFVUuR/PZ8xi3Sk7R0nHqYGd2fv3wwh7ne2jVuSJBz37kFIbW70Git82226QHdK9W0ykY0MSEk4xG5qlkNoB87snNyCDXynPxcC0vLn5Rg2Ic1BQV33/86S14lD9pyE5UdnqMXz5ZV0BFU5PmU63MKarBPMCQJZp9m+IZhUAAMT8E3bM9kfegr1duNEUA7fW1e0ypbWGAxgMMuYpGPvFk/j/xkxZrnjXvZhYCO4a3elGucO7sJkrhkTo5knApRcPtnBvo+sl5S/qHeZMX3KsAiRogxIaY8ht+g=
  on:
    tags: true
    repo: scopeta/focusedme
    python: 3.8
